services:
  nginx:
    build:
      context: ./apiGateway
      dockerfile: nginx.dockerfile
    ports:
      - "3008:3008"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db-data/mongo/:/data/db
